### ISSUE TITLE
Something more interesting? =)

### ISSUE THREAD

**Issue by TovarischSukhov** [paskag/mybot#1]
https://github.com/paskag/mybot/blob/887967208eefbe8396f2afed1a6ac2374f74dfa3/bot.py#L20

А давай тут сделаем, чтобы бот отвечал случайно 
1. либо заготовленной фразой
2. Либо повторял, что ему прислали + 'говоришь ты, а я что, я примус починяю'
3. Переворачивал то, что ему приходит -- например привет - тевирп. Есть два варианта, можно переворачивать каждое слово в отдельности, но сохранять порядок слов (сложнее), можно переворачивать все вместе

Это дополнительное задание, можно придумать еще каких-то вариантов =)

**Comment by paskag** [comment]
Выполнил и запушил!
